// Scores pxtree against the planted bugs in bench/pages.
//   node bench/run.mjs                  score every page and rewrite the generated part of bench/RESULTS.md
//   node bench/run.mjs --screenshots    only take PNGs into bench/shots, text output goes to files next to them
//   node bench/run.mjs pricing chat     limit either mode to these pages

import { execFile } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const runFile = promisify(execFile);

const benchDirectory = dirname(fileURLToPath(import.meta.url));
const pagesDirectory = join(benchDirectory, 'pages');
const screenshotsDirectory = join(benchDirectory, 'shots');
const cliPath = join(benchDirectory, '..', 'dist', 'cli.js');
const resultsPath = join(benchDirectory, 'RESULTS.md');
const noiseJudgmentsPath = join(benchDirectory, 'noise-judgments.json');
const screenshotBaselinePath = join(benchDirectory, 'screenshot-baseline.json');

const generatedStartMarker = '<!-- generated by bench/run.mjs: start -->';
const generatedEndMarker = '<!-- generated by bench/run.mjs: end -->';

// Rough vision token cost of one viewport PNG, as estimated in the brief.
const screenshotTokensByViewport = { '1280x800': 1100, '390x844': 550 };

const commandLineArguments = process.argv.slice(2);
const isScreenshotMode = commandLineArguments.includes('--screenshots');
const selectedPageNames = commandLineArguments.filter(argument => !argument.startsWith('--'));

function readJsonIfPresent(path, fallback) {
  if (!existsSync(path)) return fallback;

  return JSON.parse(readFileSync(path, 'utf8'));
}

function readPages() {
  const expectationFileNames = readdirSync(pagesDirectory).filter(fileName => fileName.endsWith('.expect.json')).sort();
  const pages = expectationFileNames.map(fileName => {
    const pageName = fileName.replace('.expect.json', '');
    const expectation = JSON.parse(readFileSync(join(pagesDirectory, fileName), 'utf8'));

    return { pageName, htmlPath: join(pagesDirectory, `${pageName}.html`), ...expectation };
  });

  if (selectedPageNames.length === 0) return pages;

  return pages.filter(page => selectedPageNames.includes(page.pageName));
}

function getRunViewport(runArguments) {
  const viewportFlagIndex = runArguments.indexOf('--viewport');

  return viewportFlagIndex === -1 ? '1280x800' : runArguments[viewportFlagIndex + 1];
}

async function runPxtree(htmlPath, runArguments) {
  const startTime = performance.now();
  const { stdout } = await runFile('node', [cliPath, htmlPath, '--no-diff', ...runArguments], { maxBuffer: 64 * 1024 * 1024 });
  const wallMilliseconds = Math.round(performance.now() - startTime);

  return { output: stdout, wallMilliseconds };
}

function getSummaryLines(output) {
  const summaryLines = [];
  let isInsideSummary = false;

  for (const line of output.split('\n')) {
    if (line.startsWith('summary:')) {
      isInsideSummary = true;
      continue;
    }

    if (isInsideSummary && line.startsWith('  ')) {
      summaryLines.push(line.trim());
      continue;
    }

    isInsideSummary = false;
  }

  return summaryLines;
}

// A bug's match is one list of substrings that must all be on one line, or a list of such lists where any one may match.
function getMatchAlternatives(bug) {
  return Array.isArray(bug.match[0]) ? bug.match : [bug.match];
}

function isLineMatchingBug(line, bug) {
  return getMatchAlternatives(bug).some(expectedSubstrings => expectedSubstrings.every(expectedSubstring => line.includes(expectedSubstring)));
}

function describeMatch(bug) {
  return getMatchAlternatives(bug)
    .map(expectedSubstrings => expectedSubstrings.map(expectedSubstring => `\`${expectedSubstring}\``).join(' + '))
    .join(' or ');
}

function getMedian(numbers) {
  const sortedNumbers = [...numbers].sort((first, second) => first - second);
  const middleIndex = Math.floor(sortedNumbers.length / 2);

  if (sortedNumbers.length % 2 === 1) return sortedNumbers[middleIndex];

  return Math.round((sortedNumbers[middleIndex - 1] + sortedNumbers[middleIndex]) / 2);
}

async function takeScreenshots(pages) {
  mkdirSync(screenshotsDirectory, { recursive: true });

  for (const page of pages) {
    for (const [runName, runArguments] of Object.entries(page.runs)) {
      const screenshotPath = join(screenshotsDirectory, `${page.pageName}.${runName}.png`);
      const { output } = await runPxtree(page.htmlPath, [...runArguments, '--screenshot', screenshotPath]);

      writeFileSync(join(screenshotsDirectory, `${page.pageName}.${runName}.txt`), output);
      console.log(screenshotPath);
    }
  }
}

async function scorePage(page) {
  const runResults = {};

  for (const [runName, runArguments] of Object.entries(page.runs)) {
    const { output, wallMilliseconds } = await runPxtree(page.htmlPath, runArguments);

    runResults[runName] = {
      runName,
      viewport: getRunViewport(runArguments),
      output,
      wallMilliseconds,
      lineCount: output.trimEnd().split('\n').length,
      characterCount: output.length,
      approximateTokens: Math.round(output.length / 4),
      summaryLines: getSummaryLines(output),
    };
  }

  const bugResults = page.bugs.map(bug => {
    const outputLines = runResults[bug.run].output.split('\n');
    const matchingLine = outputLines.find(line => isLineMatchingBug(line, bug));

    return { ...bug, isFound: matchingLine !== undefined, matchingLine: matchingLine?.trim() };
  });

  const allSummaryLines = Object.values(runResults).flatMap(runResult =>
    runResult.summaryLines.map(summaryLine => ({ runName: runResult.runName, summaryLine })),
  );
  const noiseLinesByText = new Map();

  for (const { runName, summaryLine } of allSummaryLines) {
    const isExpected = page.bugs.some(bug => isLineMatchingBug(summaryLine, bug));
    if (isExpected) continue;

    const existingNoise = noiseLinesByText.get(summaryLine);

    if (existingNoise) {
      existingNoise.runNames.push(runName);
    } else {
      noiseLinesByText.set(summaryLine, { summaryLine, runNames: [runName] });
    }
  }

  return { ...page, runResults: Object.values(runResults), bugResults, noiseLines: [...noiseLinesByText.values()] };
}

function createMarkdownTable(headerCells, rows) {
  const headerLine = `| ${headerCells.join(' | ')} |`;
  const separatorLine = `| ${headerCells.map(() => '---').join(' | ')} |`;
  const rowLines = rows.map(rowCells => `| ${rowCells.join(' | ')} |`);

  return [headerLine, separatorLine, ...rowLines].join('\n');
}

function escapeTableCell(text) {
  return String(text).replaceAll('|', '\\|').replaceAll('`', "'");
}

function createReport(scoredPages) {
  const noiseJudgments = readJsonIfPresent(noiseJudgmentsPath, {});
  const screenshotBaseline = readJsonIfPresent(screenshotBaselinePath, {});

  const allRunResults = scoredPages.flatMap(page => page.runResults);
  const allBugResults = scoredPages.flatMap(page => page.bugResults.map(bug => ({ ...bug, pageName: page.pageName })));
  const foundBugCount = allBugResults.filter(bug => bug.isFound).length;
  const buggyPages = scoredPages.filter(page => !page.clean);
  const cleanPages = scoredPages.filter(page => page.clean);

  const getNoisePerPage = pages => (pages.length === 0 ? 0 : pages.reduce((total, page) => total + page.noiseLines.length, 0) / pages.length);

  const perPageRows = scoredPages.map(page => [
    page.pageName + (page.clean ? ' (clean)' : ''),
    page.runResults.map(runResult => runResult.runName).join(', '),
    page.bugs.length,
    page.bugResults.filter(bug => bug.isFound).length,
    page.bugResults.filter(bug => !bug.isFound).length,
    page.noiseLines.length,
    page.runResults.map(runResult => runResult.wallMilliseconds).join(' / '),
    page.runResults.map(runResult => runResult.lineCount).join(' / '),
    page.runResults.map(runResult => runResult.approximateTokens).join(' / '),
  ]);

  const totalLines = [
    `bugs planted ${allBugResults.length}, found ${foundBugCount}, recall ${((foundBugCount / allBugResults.length) * 100).toFixed(0)}%`,
    `noise lines per buggy page ${getNoisePerPage(buggyPages).toFixed(1)}, per clean page ${getNoisePerPage(cleanPages).toFixed(1)}`,
    `runs ${allRunResults.length}, median wall time ${getMedian(allRunResults.map(runResult => runResult.wallMilliseconds))} ms, median output ${getMedian(allRunResults.map(runResult => runResult.lineCount))} lines, median approx tokens ${getMedian(allRunResults.map(runResult => runResult.approximateTokens))}`,
  ];

  const bugKinds = [...new Set(allBugResults.map(bug => bug.kind))];
  const perKindRows = bugKinds.map(kind => {
    const bugsOfKind = allBugResults.filter(bug => bug.kind === kind);
    const screenshotVerdicts = bugsOfKind.map(bug => screenshotBaseline[bug.pageName]?.[bug.selector]).filter(Boolean);
    const seenByScreenshotCount = screenshotVerdicts.filter(verdict => verdict.isSeen).length;
    const screenshotCell = screenshotVerdicts.length === 0 ? 'not recorded' : `${seenByScreenshotCount}/${bugsOfKind.length}`;

    return [kind, bugsOfKind.length, `${bugsOfKind.filter(bug => bug.isFound).length}/${bugsOfKind.length}`, screenshotCell];
  });

  const perBugRows = allBugResults.map(bug => {
    const screenshotVerdict = screenshotBaseline[bug.pageName]?.[bug.selector];
    const screenshotCell = screenshotVerdict ? (screenshotVerdict.isSeen ? 'yes' : 'no') : 'not recorded';

    const textCell = bug.isFound ? `yes: ${escapeTableCell(bug.matchingLine)}` : 'no';

    return [bug.pageName, escapeTableCell(bug.kind), bug.run, textCell, screenshotCell, escapeTableCell(screenshotVerdict?.note ?? '')];
  });

  const missLines = allBugResults
    .filter(bug => !bug.isFound)
    .map(bug => `- ${bug.pageName} / ${bug.kind} / run ${bug.run}: expected one line with ${describeMatch(bug)} (${bug.note})`);

  const amendedLines = allBugResults
    .filter(bug => bug.amended)
    .map(bug => `- ${bug.pageName} / ${bug.kind}: now ${describeMatch(bug)}. ${bug.amended}`);

  const noiseLines = scoredPages.flatMap(page =>
    page.noiseLines.map(noise => {
      const judgment = noiseJudgments[page.pageName]?.[noise.summaryLine] ?? 'not judged yet';

      return `- ${page.pageName} [${noise.runNames.join(', ')}] \`${noise.summaryLine}\` : ${judgment}`;
    }),
  );

  const screenshotCostRows = Object.entries(screenshotTokensByViewport).map(([viewport, tokens]) => {
    const textRuns = allRunResults.filter(runResult => runResult.viewport === viewport);
    const medianTextTokens = textRuns.length === 0 ? 'n/a' : getMedian(textRuns.map(runResult => runResult.approximateTokens));

    return [viewport, `~${tokens} (estimate)`, medianTextTokens];
  });

  return [
    generatedStartMarker,
    '',
    '## Totals',
    '',
    ...totalLines.map(line => `- ${line}`),
    '',
    '## Per page',
    '',
    'Times, lines and tokens are per run, in the order of the runs column. Tokens are characters divided by 4.',
    '',
    createMarkdownTable(['page', 'runs', 'bugs', 'found', 'missed', 'noise', 'ms', 'lines', 'tokens'], perPageRows),
    '',
    '## Per bug kind',
    '',
    createMarkdownTable(['kind', 'planted', 'found by text', 'seen in screenshot'], perKindRows),
    '',
    '## Per bug',
    '',
    createMarkdownTable(['page', 'kind', 'run', 'text (matching line)', 'screenshot', 'screenshot note'], perBugRows),
    '',
    '## Cost of a screenshot versus the text',
    '',
    createMarkdownTable(['viewport', 'screenshot tokens', 'median text tokens'], screenshotCostRows),
    '',
    '## Misses',
    '',
    ...(missLines.length === 0 ? ['None.'] : missLines),
    '',
    '## Expectations amended after the first scoring pass',
    '',
    ...(amendedLines.length === 0 ? ['None.'] : amendedLines),
    '',
    '## Noise lines',
    '',
    'Every summary line that matches no planted bug, once per page, with the runs that printed it and the judgment from bench/noise-judgments.json.',
    '',
    ...(noiseLines.length === 0 ? ['None.'] : noiseLines),
    '',
    generatedEndMarker,
  ].join('\n');
}

function writeResults(generatedReport) {
  if (!existsSync(resultsPath)) {
    writeFileSync(resultsPath, `# pxtree benchmark results\n\n${generatedReport}\n`);
    return;
  }

  const existingResults = readFileSync(resultsPath, 'utf8');
  const generatedStartIndex = existingResults.indexOf(generatedStartMarker);
  const generatedEndIndex = existingResults.indexOf(generatedEndMarker);

  if (generatedStartIndex === -1 || generatedEndIndex === -1) {
    writeFileSync(resultsPath, `${existingResults.trimEnd()}\n\n${generatedReport}\n`);
    return;
  }

  const textBeforeReport = existingResults.slice(0, generatedStartIndex);
  const textAfterReport = existingResults.slice(generatedEndIndex + generatedEndMarker.length);
  writeFileSync(resultsPath, textBeforeReport + generatedReport + textAfterReport);
}

function printPageTable(scoredPage) {
  console.log(`\n${scoredPage.pageName}${scoredPage.clean ? ' (clean)' : ''}`);

  for (const runResult of scoredPage.runResults) {
    console.log(`  run ${runResult.runName.padEnd(8)} ${String(runResult.wallMilliseconds).padStart(6)} ms ${String(runResult.lineCount).padStart(4)} lines ${String(runResult.approximateTokens).padStart(6)} tokens`);
  }

  for (const bug of scoredPage.bugResults) {
    console.log(`  ${bug.isFound ? 'found ' : 'MISSED'} ${bug.kind} (${bug.run})${bug.isFound ? `  <- ${bug.matchingLine}` : ''}`);
  }

  for (const noise of scoredPage.noiseLines) {
    console.log(`  noise  ${noise.summaryLine}`);
  }
}

const pages = readPages();

if (isScreenshotMode) {
  await takeScreenshots(pages);
} else {
  const scoredPages = [];

  for (const page of pages) {
    const scoredPage = await scorePage(page);
    printPageTable(scoredPage);
    scoredPages.push(scoredPage);
  }

  const generatedReport = createReport(scoredPages);
  console.log(`\n${generatedReport.split('## Per page')[0].replace(generatedStartMarker, '').trim()}`);

  if (selectedPageNames.length === 0) {
    writeResults(generatedReport);
  }
}
